apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway
      containers:
      - name: envoy
        image: ghcr.io/yolean/envoy:distroless-v1.37.0@sha256:92fdb97b9fdb47da82fbe3651b83bd1419e544966d264632af4864004652685f
        ports:
        - name: http
          containerPort: 8080
        - name: admin
          containerPort: 9901
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
          readOnly: true
      - name: xds
        image: yolean/gateway-sidecar:latest
        imagePullPolicy: Never
        env:
        - name: GATEWAY_HOSTNAME
          value: localhost
        ports:
        - name: xds
          containerPort: 18000
        - name: api
          containerPort: 18080
      volumes:
      - name: config
        configMap:
          name: gateway-envoy
