# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ui

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

configMapGenerator:
- name: gateway-envoy
  files:
  - envoy.yaml
- name: duckdb-envoy
  options:
    disableNameSuffixHash: true
  files:
  - envoy.yaml=duckdb-envoy.yaml
