name: fluentbit

on:
  push:
    branches: [main]
    paths:
    - .github/workflows/fluentbit.yaml
    - images/fluentbit/Dockerfile
    - images/fluentbit/*.patch
  pull_request:
    paths:
    - .github/workflows/fluentbit.yaml
    - images/fluentbit/Dockerfile
    - images/fluentbit/*.patch

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      if: github.event_name == 'push'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ghcr.io/yolean/fluentbit
        tags: |
          type=raw,value=${{ github.sha }}

    - uses: docker/build-push-action@v6
      with:
        context: images/fluentbit
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=fluentbit
        cache-to: type=gha,mode=max,scope=fluentbit

    - uses: docker/metadata-action@v5
      id: meta-debug
      with:
        images: ghcr.io/yolean/fluentbit
        tags: |
          type=raw,value=debug-${{ github.sha }}

    - uses: docker/build-push-action@v6
      with:
        context: images/fluentbit
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: ${{ steps.meta-debug.outputs.tags }}
        labels: ${{ steps.meta-debug.outputs.labels }}
        build-args: |
          FLB_TRACE=On
          FLB_HTTP_CLIENT_DEBUG=On
        cache-from: type=gha,scope=fluentbit-debug
        cache-to: type=gha,mode=max,scope=fluentbit-debug
